### PR TITLE
Add apt-get update to download the latest version of openssh-server

### PR DESCRIPTION
**Pull request by rotilho**

### CODE REVIEW

**Comment by rotilho** [comment]
No need to merge if #21 is going to be accepted.

**Comment by wnameless** [comment]
The "apt-get update" is already existed.

**Comment by rotilho** [comment]
It was added in commit dbd94c5

However update and install should be in the same RUN otherwise we can face some issues with Docker cache. You can find more information in https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/#/apt-get

**Comment by wnameless** [comment]
Thanks for mentioning me. I just fixed it.

**Pull request closed without merging**
